<#
.SYNOPSIS
    Switch the active Copilot role for the MRMS workspace.

.DESCRIPTION
    Copies the chosen role file into .github/copilot-instructions.md so that
    GitHub Copilot loads the correct persona automatically on the next session.

.PARAMETER Role
    One of: scrum-master, architect, developer, ui-ux

.EXAMPLE
    .\switch-role.ps1 architect
    .\switch-role.ps1 developer
    .\switch-role.ps1 scrum-master
    .\switch-role.ps1 ui-ux
#>

param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateSet("scrum-master", "architect", "developer", "ui-ux")]
    [string]$Role
)

$root      = $PSScriptRoot
$roleFile  = Join-Path $root "Agents\roles\$Role.md"
$sharedSys = Join-Path $root "Agents\_shared\system-knowledge.md"
$sharedTeam= Join-Path $root "Agents\_shared\team-and-process.md"
$target    = Join-Path $root ".github\copilot-instructions.md"

if (-not (Test-Path $roleFile)) {
    Write-Error "Role file not found: $roleFile"
    exit 1
}

# Build the instructions file:
# 1. Role-specific instructions
# 2. Appended shared context inline (so Copilot sees everything in one file)
$roleContent   = Get-Content $roleFile   -Raw
$sysContent    = Get-Content $sharedSys  -Raw
$teamContent   = Get-Content $sharedTeam -Raw

$combined = @"
$roleContent

---
<!-- AUTO-GENERATED by switch-role.ps1 — DO NOT EDIT MANUALLY -->
<!-- Active role: $Role | Switched: $(Get-Date -Format 'yyyy-MM-dd HH:mm') -->

$sysContent

---

$teamContent
"@

Set-Content -Path $target -Value $combined -Encoding UTF8

Write-Host ""
Write-Host "  ✅  Active role switched to: $Role" -ForegroundColor Green
Write-Host "  📄  .github/copilot-instructions.md updated."
Write-Host "  💡  Start a new Copilot Chat session to pick up the new role."
Write-Host ""
